<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
	<title>Galery</title>
</head>
<body>
	<header>
	<nav class="navbar navbar-expand-sm bg-light navbar-light">
		<a class="navbar-brand" href="/home">Galery</a>
		<ul class="navbar-nav">
			<li class="nav-item active">
				<a class="nav-link" href="/upload">Upload</a>
			</li>
		</ul>
	</nav>
	</header>
	<br/>
	<div class="container">
		<div class="row" >
			<?php foreach($views["posts"] as $post) { ?>
					<div class="col-md-3" style="margin-right: 15px; margin-bottom: 10px;">
						<div class="card" 
						style="width: 18rem; display: inline-block;">
							<img class="card-img-top"
							style="padding: 15px 5px; width: 95%; heigth: 150px"
							src="storage/<?= $post["path_image"] ?>" alt="Card image cap">
							<div class="card-body">
								<p class="card-text text-center"><?= $post["describe"] ?> </p>
								<div class="offset-2">
									<a href="/posts/<?= $post["id"] ?>/like" class="btn btn-primary">
										<i class="fa fa-thumbs-up"></i>&nbsp; <?= $post["likes"] ?>
									</a>
									<a href="/posts/<?= $post["id"] ?>/dislike" class="btn btn-primary">
										<i class="fa fa-thumbs-down"></i>&nbsp; <?= $post["unlikes"] ?>
									</a>
									<a href="/posts/<?= $post["id"] ?>/download" class="btn btn-primary">
										<i class="fa fa-download"></i>&nbsp;
									</a>
								</div>
							</div>
						</div>
					</div>
			<?php } ?>
		</div>
	</div>
</body>
</html>
<br/>


